spring.application.name=tienda21

# Configuración de la base de datos
spring.datasource.url=jdbc:mysql://195.35.61.130:3306/u630341118_inndata_021
spring.datasource.username=u630341118_admingeneral
spring.datasource.password=Jg5/K8g5JXR
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
